from __future__ import annotations


HELP_TEXTS = {
    "trend_up_threshold": "只有趋势上行概率高于该阈值的板块才会进入候选。阈值越高，筛选越严格，但可能错过早期机会。",
    "top_n": "每次调仓时最多持有的板块数量。数量越少，组合越集中；数量越多，组合越分散。",
    "rebalance_every": "每隔多少个交易日重新选择板块。间隔越短，反应越快，但交易成本更高。",
    "train_window": "滚动训练时向前使用多少个交易日的数据。窗口越长，模型越稳定；窗口越短，对近期变化更敏感。",
    "transaction_cost": "模拟交易时的单边成本，包括手续费、滑点和冲击成本的简化估计。",
    "max_drawdown_threshold": "个股近20日从高点回撤的最大允许值。阈值越低，过滤越严格。",
    "amount_z_min": "成交额相对近20日均值的位置。0 表示接近均值，1 表示明显放量，-1 表示明显缩量。",
    "market_regime": "大盘 HMM 用于识别整体市场环境，不用于直接预测指数涨跌。",
    "use_breadth": "市场宽度能反映全市场股票的参与程度，避免指数被少数权重股遮蔽。",
    "market_start_date": "用于抓取指数数据和训练模型的起点。时间越长，模型更稳定，但对近期市场变化反应更慢。",
    "market_end_date": "用于抓取数据和训练模型的终点。通常保持为最新日期。",
    "market_indices": "选择参与大盘状态判断的主要指数。建议至少包含沪深300、中证500、中证1000，用于覆盖大盘、中盘和小盘风格。",
    "incremental_update": "开启后只更新最近缺失的数据，速度更快。关闭后会按起止日期重新抓取。",
    "lookback_days": "增量更新时向前回补的天数，用于修正最近几日可能变化的数据。",
    "market_n_states": "模型将市场划分为几个隐藏状态。默认 3 个状态：风险偏好、中性震荡、风险回避。状态过多会提高不稳定性。",
    "random_state": "控制模型初始化结果，便于复现。一般不需要修改。",
    "hmm_n_init": "用不同随机种子重复训练 HMM，并保留似然最高的一次。次数越多越稳，但训练更慢。",
    "market_filter": "当前大盘状态仅作为风险提示，不直接改变板块排序或回测仓位。",
    "stock_start_date": "没有本地行情的个股会从该日期开始更新；已有行情的个股会自动增量回补最近几天。",
    "max_stocks_to_update": "限制一次最多更新多少只个股，避免接口压力过大。",
    "missing_only": "开启后只更新本地完全没有行情的个股；关闭后会对已有个股做增量更新。",
}


COLUMN_LABELS = {
    "sector_type": "板块类型",
    "sector_name": "板块名称",
    "state_label": "当前状态",
    "state_source": "状态来源",
    "prob_trend_up": "趋势上行概率",
    "prob_neutral": "中性震荡概率",
    "prob_risk_off": "风险回避概率",
    "sector_score": "板块评分",
    "sector_tag": "板块标签",
    "feature_scope_id": "特征作用域",
    "feature_scope_type": "特征作用域类型",
    "trade_date": "交易日期",
    "ret_20d": "20日收益",
    "vol_20d": "20日波动率",
    "drawdown_20d": "20日回撤",
    "ma20_slope": "20日均线斜率",
    "next_state_probs_json": "下一状态概率",
    "score": "个股评分",
    "rs_vs_sector_20d": "相对板块强弱",
    "rs_vs_index_20d": "相对大盘强弱",
    "amount_z_20d": "成交额热度",
    "risk_flags_json": "风险提示",
    "stock_code": "股票代码",
    "stock_name": "股票名称",
    "close": "收盘价",
    "ma20": "20日均线",
    "benchmark_status": "市场基准状态",
    "condition": "筛选条件",
    "enabled": "是否启用",
    "before": "筛选前数量",
    "after": "筛选后数量",
    "removed": "剔除数量",
    "skipped_reason": "跳过原因",
    "failed_reason": "首个未入选原因",
    "interface": "接口",
    "last_network_success": "最近网络成功",
    "last_network_failure": "最近网络失败",
    "last_cache_hit": "最近缓存命中",
    "stale_reads": "过期缓存读取次数",
    "last_error": "最近错误",
    "universe_name": "板块池名称",
    "item_type": "项目类型",
    "item_id": "项目 ID",
    "item_name": "项目名称",
    "custom_stock_basket": "自定义股票池",
    "index_code": "指数代码",
    "index_name": "指数名称",
    "latest_close": "最新收盘",
    "up_ratio": "上涨家数比例",
    "above_ma20_ratio": "高于20日均线比例",
    "amount_total": "全市场成交额",
    "prob_risk_on": "风险偏好概率",
    "annual_return": "年化收益",
    "annual_return_gross": "扣费前年化收益",
    "annual_return_net": "扣费后年化收益",
    "max_drawdown": "最大回撤",
    "max_drawdown_gross": "扣费前最大回撤",
    "max_drawdown_net": "扣费后最大回撤",
    "sharpe": "夏普比率",
    "sharpe_gross": "扣费前夏普",
    "sharpe_net": "扣费后夏普",
    "calmar": "Calmar",
    "calmar_gross": "扣费前 Calmar",
    "calmar_net": "扣费后 Calmar",
    "win_rate_net": "扣费后正收益占比",
    "turnover": "换手率",
    "strategy": "策略",
    "count": "数量",
    "prev_label": "前一状态",
    "rows": "行数",
    "first_date": "起始日期",
    "last_date": "结束日期",
    "constituents": "成分股数量",
    "missing_stock_ohlcv": "缺少行情个股数",
    "missing_ratio": "缺失比例",
    "cache_hits": "缓存命中次数",
    "network_hits": "网络请求次数",
    "target_type": "目标类型",
    "board_type": "板块类型",
    "target_name": "目标名称",
    "failure_count": "失败次数",
    "last_failure": "最近失败",
    "weight": "权重",
    "note": "备注",
    "created_at": "创建时间",
    "basket_id": "股票池 ID",
    "basket_name": "股票池名称",
    "index_method": "指数计算方法",
    "member_count": "有效成员数",
    "coverage": "覆盖率",
    "coverage_level": "覆盖等级",
    "coverage_warning": "覆盖提示",
    "expected_count": "应覆盖股票数",
    "effective_count": "有效股票数",
    "total_count": "样本总数",
    "ma20_valid_count": "均线有效股票数",
    "coverage_ratio": "覆盖率",
    "breadth_mode": "宽度模式",
    "next_prob_trend_up": "下一趋势上行概率",
    "next_prob_neutral": "下一中性震荡概率",
    "next_prob_risk_off": "下一风险回避概率",
    "next_prob_risk_on": "下一风险偏好概率",
    "gap_1d": "跳空幅度",
    "intraday_ret": "日内收益",
    "is_limit_up": "近似涨停",
    "is_limit_down": "近似跌停",
    "is_one_word_limit": "一字涨停",
    "is_suspended_or_missing": "停牌或缺失",
    "consecutive_limit_up_days": "连续涨停天数",
    "consecutive_limit_down_days": "连续跌停天数",
    "horizon_days": "未来天数",
    "mean_return": "平均收益",
    "median_return": "中位数收益",
    "win_rate": "正收益占比",
    "volatility": "波动率",
    "sample_count": "样本数",
    "avg_duration_days": "平均持续天数",
    "state_share": "状态占比",
    "same_universe": "相同范围",
    "uses_transaction_cost": "使用交易成本",
    "causal_walk_forward": "因果滚动回测",
    "exec_date": "执行日期",
    "cost": "交易成本",
    "weights": "持仓权重",
    "switch_date": "切换日期",
    "from_state": "起始状态",
    "to_state": "目标状态",
    "current_state_days": "当前状态持续交易日",
    "previous_state_days": "上一状态持续交易日",
    "segment_id": "状态段 ID",
    "start_date": "开始日期",
    "end_date": "结束日期",
    "trading_days": "交易日数量",
    "calendar_days": "自然日数量",
    "segment_return": "该段收益",
    "avg_prob_trend_up": "平均趋势上行概率",
    "avg_prob_neutral": "平均中性震荡概率",
    "avg_prob_risk_off": "平均风险回避概率",
    "prev_state_label": "上一状态",
    "next_state_label": "下一状态",
    "missing_recent": "缺失最近行情",
}


VALUE_LABELS = {
    "RiskOn": "风险偏好",
    "Neutral": "中性震荡",
    "RiskOff": "风险回避",
    "TrendUp": "趋势上行",
    "in_sample_display": "样本内展示",
    "causal_backtest": "因果回测",
    "all": "全市场",
    "universe": "当前板块池",
    "custom_only": "仅自定义股票池",
    "mixed_universe": "混合板块池",
    "industry": "行业",
    "concept": "概念",
    "custom": "自定义股票池",
    "custom_stock_basket": "自定义股票池",
    "equal_weight": "等权",
    "custom_weight": "自定义权重",
    "model": "HMM 趋势策略",
    "baseline_1_rs20_top_n": "20日相对强弱轮动",
    "baseline_2_equal_weight": "全板块等权",
    "monthly": "每月",
    "quarterly": "每季度",
    "signal": "每个信号日",
    "open": "次日开盘",
    "close": "次日收盘",
    "full_market": "全市场",
    "partial_sample": "部分样本",
    "insufficient": "样本不足",
    "local_sample": "本地样本",
    "full_market_mode": "全 A 市场",
}

PROBABILITY_LABELS = {
    "prob_risk_on": "风险偏好概率",
    "prob_neutral": "中性震荡概率",
    "prob_risk_off": "风险回避概率",
    "prob_trend_up": "趋势上行概率",
}


def display_value(value):
    return VALUE_LABELS.get(str(value), value)


def display_state_label(value) -> str:
    return str(display_value(value))


def localize_display_values(df):
    if df is None or getattr(df, "empty", True):
        return df
    out = df.copy()
    for col in ["state_label", "prev_label", "prev_state_label", "next_state_label", "from_state", "to_state", "state_source", "scope_type", "feature_scope_type", "sector_type", "item_type", "strategy", "index_method", "coverage_level"]:
        if col in out.columns:
            out[col] = out[col].map(display_value)
    return out


def rename_columns_for_display(df):
    if df is None or getattr(df, "empty", True):
        return df
    localized = localize_display_values(df)
    return localized.rename(columns={col: COLUMN_LABELS.get(col, col) for col in localized.columns})
