from __future__ import annotations


HELP_TEXTS = {
    "trend_up_threshold": "只有 TrendUp 状态后验高于该阈值的板块才会进入候选。阈值越高，筛选越严格，但可能错过早期变化。",
    "top_n": "每次调仓时最多持有的板块数量。数量越少，组合越集中；数量越多，组合越分散。",
    "rebalance_every": "每隔多少个交易日重新选择板块。间隔越短，反应越快，但交易成本更高。",
    "train_window": "滚动训练时向前使用多少个交易日的数据。窗口越长，模型越稳定；窗口越短，对近期变化更敏感。",
    "transaction_cost": "模拟交易时的单边成本，包括手续费、滑点和冲击成本的简化估计。",
    "max_drawdown_threshold": "个股近20日从高点回撤的最大允许值。阈值越低，过滤越严格。",
    "amount_z_min": "成交额相对近20日均值的位置。0 表示接近均值，1 表示明显放量，-1 表示明显缩量。",
    "market_regime": "大盘 HMM 用于识别整体市场环境，不用于直接预测指数涨跌。",
    "use_breadth": "市场宽度能反映全市场股票的参与程度，避免指数被少数权重股遮蔽。",
    "market_start_date": "用于抓取指数数据和训练模型的起点。时间越长，模型更稳定，但对近期市场变化反应更慢。",
    "market_end_date": "用于抓取数据和训练模型的终点。通常保持为最新日期。",
    "market_indices": "选择参与大盘状态判断的主要指数。建议至少包含沪深300、中证500、中证1000，用于覆盖大盘、中盘和小盘风格。",
    "incremental_update": "开启后只更新最近缺失的数据，速度更快。关闭后会按起止日期重新抓取。",
    "lookback_days": "增量更新时向前回补的天数，用于修正最近几日可能变化的数据。",
    "market_n_states": "模型将市场划分为几个隐藏状态。默认 3 个状态：风险偏好、中性震荡、压力状态。状态过多会提高不稳定性。",
    "random_state": "控制模型初始化结果，便于复现。一般不需要修改。",
    "hmm_n_init": "用不同随机种子重复训练 HMM，并保留似然最高的一次。次数越多越稳，但训练更慢。",
    "market_filter": "当前大盘状态仅作为风险提示，不直接改变板块排序或回测仓位。",
    "stock_start_date": "没有本地行情的个股会从该日期开始更新；已有行情的个股会自动增量回补最近几天。",
    "max_stocks_to_update": "限制一次最多更新多少只个股，避免接口压力过大。",
    "missing_only": "开启后只更新本地完全没有行情的个股；关闭后会对已有个股做增量更新。",
}


METRIC_HELP_TEXTS = {
    "信号日期": "当前信号面板所使用的最新交易日。页面里的状态、波动率和风险分层都应理解为这个日期上的可用信息。",
    "数据新鲜度": "说明信号计算是否使用了最新可得行情。若不是最新可得数据，后续状态和风险分层都需要谨慎解读。",
    "来源范围": "说明这条信号来自全市场、当前板块池，还是某个限定样本范围。不同范围之间不宜直接比较数量。",
    "基准风险分层": "用只读行情和波动率规则给出的风险层级，是模型覆盖之外的基础风险参照。",
    "HMM 状态": "板块 HMM 对当前市场/板块状态的离散划分，例如 TrendUp、中性震荡或压力状态。它是状态解释，不是买卖指令。",
    "HMM 状态来源": "说明 HMM 状态来自因果滚动缓存、样本内展示，还是当前不可用。用于判断这条状态能否参与回测解释。",
    "HMM 状态置信度": "HMM 对当前展示状态的后验概率。数值越高表示模型越集中地判断为该状态，但不等于上涨或下跌概率。",
    "HSMM 生命周期覆盖": "信号面板中具备 HSMM 生命周期上下文的板块数量。覆盖不足时，生命周期相关解释只适用于已有覆盖的板块。",
    "HSMM 生命周期阶段": "把当前状态段按持续时间划分为早期、成熟期或后期，用于解释状态是否已经延续较久。",
    "HSMM 状态持续天数": "当前 HSMM 状态已经连续持续的交易日数量。它描述状态年龄，不直接代表未来还能持续多久。",
    "HSMM 持续时长分桶": "把状态持续时间放入短、中、长等区间，便于和历史状态段比较。",
    "HSMM 持续时长分位": "当前状态持续时间在历史同类状态段中的相对位置。分位越高，表示这个状态段已经比多数历史样本更长。",
    "Stage03V 来源": "说明 Stage03V 风险分数是否有当前实体级来源。不可用时，页面只展示基准或研究性上下文。",
    "Stage03V 概率来源状态": "说明当前是否存在可用于展示校准概率的实体级分数来源。不可用时不会展示数值概率。",
    "Stage03V 概率显示状态": "说明 Stage03V 概率是可显示、仅序数展示、仅基准展示，还是因证据不足被隐藏。",
    "Stage03V 风险序数": "Stage03V 给出的相对风险等级，只表达排序或分层，不应当被读成精确概率。",
    "校准概率是否可显示": "说明当前行是否通过就绪门控，允许展示经过校准的数值概率。",
    "校准概率字段": "列出当前可展示的校准概率字段。没有字段时，说明该行只能做非数值解释。",
    "模型-基准一致性": "比较模型覆盖与基准波动率风险是否方向一致。若不一致，需要优先做人工复核，而不是机械采信单一来源。",
    "人工复核提示": "把模型和基准之间的关系翻译成复核线索，用来提示可能的误报、残余风险或覆盖缺口。",
    "非交易输出": "明确当前页面输出不是交易、仓位、买卖或执行建议，只能作为研究和人工判断参考。",
    "20日波动率": "用近 20 个交易日收益计算的短期波动强度。更敏感，但也更容易受短期冲击影响。",
    "60日波动率": "用近 60 个交易日收益计算的中期波动强度。比 20 日波动率更平滑，反应速度较慢。",
    "EWMA 波动率": "指数加权移动波动率，对近期波动赋予更高权重，用来更快捕捉风险抬升或下降。",
    "波动率分层": "把波动率映射为低、正常、偏高、高等等级，便于快速比较风险水平。",
    "横截面波动率分位": "当前板块波动率在同一信号日所有板块中的相对位置。分位越高，说明相对其他板块越波动。",
    "时间序列波动率分位": "当前波动率相对于该板块自身历史波动的相对位置。用于判断是否高于自己的常态。",
    "波动率主来源": "说明当前风险分层优先使用哪类波动率或行情来源。",
    "波动率信号状态": "说明波动率信号是否可用，以及不可用时的主要原因。",
    "20日下行波动": "只看近 20 个交易日负收益日贡献的波动，用来观察下跌方向的风险压力。",
    "60日下行波动": "只看近 60 个交易日负收益日贡献的波动，比 20 日下行波动更平滑。",
    "20日下行波动占比": "下行波动在总波动中的占比。占比越高，说明波动更多来自下跌日。",
    "60日下行波动占比": "中期窗口内下行波动在总波动中的占比，用于观察风险是否持续偏向下行。",
    "20日负收益日占比": "近 20 个交易日中收跌天数的比例。它描述下跌频率，不描述跌幅大小。",
    "60日负收益日占比": "近 60 个交易日中收跌天数的比例，用于观察中期下跌频率。",
    "下行不对称分层": "根据下行波动占比和负收益日占比，对风险是否偏向下行做分层。",
    "最近状态切换日": "HMM 最近一次从上一状态切换到当前状态的日期。",
    "近期是否切换": "说明当前状态是否刚发生切换。刚切换的状态通常需要更多观察确认。",
    "1日退出倾向": "HSMM 对当前状态在未来 1 个交易日内结束倾向的研究性描述，不是交易概率。",
    "3日退出倾向": "HSMM 对当前状态在未来 3 个交易日内结束倾向的研究性描述。",
    "5日退出倾向": "HSMM 对当前状态在未来 5 个交易日内结束倾向的研究性描述。",
    "10日退出倾向": "HSMM 对当前状态在未来 10 个交易日内结束倾向的研究性描述。",
    "20日退出倾向": "HSMM 对当前状态在未来 20 个交易日内结束倾向的研究性描述。",
    "下一状态倾向": "HSMM 根据历史同类状态段给出的下一状态倾向，只能作为状态迁移解释。",
    "HSMM 概率显示策略": "说明 HSMM 相关概率或倾向是否允许展示，以及展示时的证据边界。",
    "Stage03V 就绪摘要": "汇总 Stage03V 当前有多少切片可显示概率、仅序数、仅基准或仅研究。",
    "可显示概率切片数": "通过门控并允许展示数值概率的 Stage03V 切片数量。",
    "仅序数切片数": "只能展示风险序数、不能展示数值概率的 Stage03V 切片数量。",
    "仅基准切片数": "只能使用基准风险参照、不能使用模型概率的 Stage03V 切片数量。",
    "仅研究切片数": "证据不足以进入展示或决策辅助，只能保留为研究观察的切片数量。",
    "数据状态": "综合网络成功时间、缓存状态、模型 run、特征范围和市场宽度后的健康判断。",
    "最近网络成功": "最近一次数据接口成功联网返回的时间。它用来判断当前数据是否可能落后。",
    "当前 stale 接口": "当前仍依赖过期缓存兜底的接口数量。数量越高，越需要先检查数据源。",
    "历史 stale 次数": "历史上发生过网络失败后读取过期缓存的累计次数。它不一定代表当前仍异常。",
    "run 范围": "当前页面关联的 HMM run 训练范围，例如全市场或某个板块池。",
    "feature scope": "当前 HMM run 使用的特征作用域。all 表示全市场特征范围，板块池模式下会显示对应范围。",
    "宽度": "市场宽度数据的覆盖口径和覆盖等级。全市场宽度比本地样本宽度更适合解释大盘状态。",
    "大盘模型用宽度": "说明最新大盘 HMM 训练时是否实际使用了市场宽度特征。",
    "问题": "阻止当前数据状态被视为完整的关键缺口。",
    "提示": "当前仍可使用，但需要留意的质量或覆盖风险。",
}


COLUMN_LABELS = {
    "sector_type": "板块类型",
    "sector_name": "板块名称",
    "state_label": "当前状态",
    "state_source": "状态来源",
    "prob_trend_up": "TrendUp 状态后验",
    "prob_neutral": "中性状态后验",
    "prob_risk_off": "压力状态后验",
    "sector_score": "板块评分",
    "sector_tag": "板块标签",
    "feature_scope_id": "特征作用域",
    "feature_scope_type": "特征作用域类型",
    "trade_date": "交易日期",
    "ret_20d": "20日收益",
    "vol_20d": "20日波动率",
    "vol_60d": "60日波动率",
    "ewma_vol": "EWMA 波动率",
    "volatility_band": "波动率分层",
    "volatility_percentile_cs": "横截面波动率分位",
    "volatility_percentile_ts_if_available": "时间序列波动率分位",
    "volatility_primary_source": "波动率主来源",
    "volatility_signal_status": "波动率信号状态",
    "downside_vol_20d": "20日下行波动",
    "downside_vol_60d": "60日下行波动",
    "downside_vol_share_20d": "20日下行波动占比",
    "downside_vol_share_60d": "60日下行波动占比",
    "negative_return_day_share_20d": "20日负收益日占比",
    "negative_return_day_share_60d": "60日负收益日占比",
    "downside_asymmetry_band": "下行不对称分层",
    "drawdown_20d": "20日回撤",
    "ma20_slope": "20日均线斜率",
    "hmm_state_label": "HMM 状态",
    "hmm_state_source": "HMM 状态来源",
    "hmm_confidence": "HMM 状态置信度",
    "recent_state_switch_date": "最近状态切换日",
    "recent_state_switch_flag": "近期是否切换",
    "hsmm_state_phase": "HSMM 生命周期阶段",
    "hsmm_state_age_days": "HSMM 状态持续天数",
    "hsmm_age_bucket": "HSMM 持续时长分桶",
    "hsmm_duration_percentile": "HSMM 持续时长分位",
    "exit_tendency_1d": "1日退出倾向",
    "exit_tendency_3d": "3日退出倾向",
    "exit_tendency_5d": "5日退出倾向",
    "exit_tendency_10d": "10日退出倾向",
    "exit_tendency_20d": "20日退出倾向",
    "next_state_tendency": "下一状态倾向",
    "hsmm_probability_display_policy": "HSMM 概率显示策略",
    "stage03v_readiness_summary": "Stage03V 就绪摘要",
    "stage03v_usable_probability_slice_count": "可显示概率切片数",
    "stage03v_ordinal_only_slice_count": "仅序数切片数",
    "stage03v_baseline_only_slice_count": "仅基准切片数",
    "stage03v_research_only_slice_count": "仅研究切片数",
    "stage03v_probability_display_status": "Stage03V 概率显示状态",
    "stage03v_probability_source_status": "Stage03V 概率来源状态",
    "stage03v_risk_ordinal": "Stage03V 风险序数",
    "stage03v_calibrated_probability_available": "校准概率是否可显示",
    "stage03v_calibrated_probability_fields": "校准概率字段",
    "model_baseline_alignment_status": "模型-基准一致性",
    "human_review_note": "人工复核提示",
    "not_trading_output": "非交易输出",
    "next_state_probs_json": "模型迁移分布 JSON",
    "score": "个股评分",
    "rs_vs_sector_20d": "相对板块强弱",
    "rs_vs_index_20d": "相对大盘强弱",
    "amount_z_20d": "成交额热度",
    "risk_flags_json": "风险提示",
    "stock_code": "股票代码",
    "stock_name": "股票名称",
    "close": "收盘价",
    "ma20": "20日均线",
    "benchmark_status": "市场基准状态",
    "condition": "筛选条件",
    "enabled": "是否启用",
    "before": "筛选前数量",
    "after": "筛选后数量",
    "removed": "剔除数量",
    "skipped_reason": "跳过原因",
    "failed_reason": "首个未入选原因",
    "interface": "接口",
    "last_network_success": "最近网络成功",
    "last_network_failure": "最近网络失败",
    "last_cache_hit": "最近缓存命中",
    "stale_reads": "过期缓存读取次数",
    "last_error": "最近错误",
    "universe_name": "板块池名称",
    "item_type": "项目类型",
    "item_id": "项目 ID",
    "item_name": "项目名称",
    "custom_stock_basket": "自定义股票池",
    "index_code": "指数代码",
    "index_name": "指数名称",
    "latest_close": "最新收盘",
    "up_ratio": "上涨家数比例",
    "above_ma20_ratio": "高于20日均线比例",
    "amount_total": "全市场成交额",
    "prob_risk_on": "风险偏好状态后验",
    "annual_return": "年化收益",
    "annual_return_gross": "扣费前年化收益",
    "annual_return_net": "扣费后年化收益",
    "max_drawdown": "最大回撤",
    "max_drawdown_gross": "扣费前最大回撤",
    "max_drawdown_net": "扣费后最大回撤",
    "sharpe": "夏普比率",
    "sharpe_gross": "扣费前夏普",
    "sharpe_net": "扣费后夏普",
    "calmar": "Calmar",
    "calmar_gross": "扣费前 Calmar",
    "calmar_net": "扣费后 Calmar",
    "win_rate_net": "扣费后正收益占比",
    "turnover": "换手率",
    "strategy": "策略",
    "count": "数量",
    "prev_label": "前一状态",
    "rows": "行数",
    "first_date": "起始日期",
    "last_date": "结束日期",
    "constituents": "成分股数量",
    "missing_stock_ohlcv": "缺少行情个股数",
    "missing_ratio": "缺失比例",
    "cache_hits": "缓存命中次数",
    "network_hits": "网络请求次数",
    "target_type": "目标类型",
    "board_type": "板块类型",
    "target_name": "目标名称",
    "failure_count": "失败次数",
    "last_failure": "最近失败",
    "weight": "权重",
    "note": "备注",
    "created_at": "创建时间",
    "basket_id": "股票池 ID",
    "basket_name": "股票池名称",
    "index_method": "指数计算方法",
    "member_count": "有效成员数",
    "coverage": "覆盖率",
    "coverage_level": "覆盖等级",
    "coverage_warning": "覆盖提示",
    "expected_count": "应覆盖股票数",
    "effective_count": "有效股票数",
    "total_count": "样本总数",
    "ma20_valid_count": "均线有效股票数",
    "coverage_ratio": "覆盖率",
    "breadth_mode": "宽度模式",
    "next_prob_trend_up": "模型迁移分布：TrendUp",
    "next_prob_neutral": "模型迁移分布：中性状态",
    "next_prob_risk_off": "模型迁移分布：压力状态",
    "next_prob_risk_on": "模型迁移分布：风险偏好",
    "gap_1d": "跳空幅度",
    "intraday_ret": "日内收益",
    "is_limit_up": "近似涨停",
    "is_limit_down": "近似跌停",
    "is_one_word_limit": "一字涨停",
    "is_suspended_or_missing": "停牌或缺失",
    "consecutive_limit_up_days": "连续涨停天数",
    "consecutive_limit_down_days": "连续跌停天数",
    "horizon_days": "未来天数",
    "mean_return": "平均收益",
    "median_return": "中位数收益",
    "win_rate": "正收益占比",
    "volatility": "波动率",
    "sample_count": "样本数",
    "avg_duration_days": "平均持续天数",
    "state_share": "状态占比",
    "same_universe": "相同范围",
    "uses_transaction_cost": "使用交易成本",
    "causal_walk_forward": "因果滚动回测",
    "exec_date": "执行日期",
    "cost": "交易成本",
    "weights": "持仓权重",
    "switch_date": "切换日期",
    "from_state": "起始状态",
    "to_state": "目标状态",
    "current_state_days": "当前状态持续交易日",
    "previous_state_days": "上一状态持续交易日",
    "segment_id": "状态段 ID",
    "start_date": "开始日期",
    "end_date": "结束日期",
    "trading_days": "交易日数量",
    "calendar_days": "自然日数量",
    "segment_return": "该段收益",
    "avg_prob_trend_up": "平均 TrendUp 状态后验",
    "avg_prob_neutral": "平均中性状态后验",
    "avg_prob_risk_off": "平均压力状态后验",
    "prev_state_label": "上一展示状态",
    "next_state_label": "后一展示状态",
    "missing_recent": "缺失最近行情",
}


VALUE_LABELS = {
    "RiskOn": "风险偏好",
    "Neutral": "中性震荡",
    "RiskOff": "压力状态",
    "TrendUp": "TrendUp 状态",
    "in_sample_display": "样本内展示",
    "causal_backtest": "因果回测",
    "all": "全市场",
    "universe": "当前板块池",
    "custom_only": "仅自定义股票池",
    "mixed_universe": "混合板块池",
    "industry": "行业",
    "concept": "概念",
    "custom": "自定义股票池",
    "custom_stock_basket": "自定义股票池",
    "equal_weight": "等权",
    "custom_weight": "自定义权重",
    "model": "HMM 趋势策略",
    "baseline_1_rs20_top_n": "20日相对强弱轮动",
    "baseline_2_equal_weight": "全板块等权",
    "monthly": "每月",
    "quarterly": "每季度",
    "signal": "每个信号日",
    "open": "次日开盘",
    "close": "次日收盘",
    "full_market": "全市场",
    "partial_sample": "部分样本",
    "insufficient": "样本不足",
    "local_sample": "本地样本",
    "full_market_mode": "全 A 市场",
}

PROBABILITY_LABELS = {
    "prob_risk_on": "风险偏好状态后验",
    "prob_neutral": "中性震荡状态后验",
    "prob_risk_off": "压力状态后验",
    "prob_trend_up": "TrendUp 状态后验",
}


def display_value(value):
    return VALUE_LABELS.get(str(value), value)


def explain_term(value):
    key = str(value)
    label = COLUMN_LABELS.get(key, key)
    return METRIC_HELP_TEXTS.get(key) or METRIC_HELP_TEXTS.get(label) or HELP_TEXTS.get(key)


def display_state_label(value) -> str:
    return str(display_value(value))


def localize_display_values(df):
    if df is None or getattr(df, "empty", True):
        return df
    out = df.copy()
    for col in ["state_label", "prev_label", "prev_state_label", "next_state_label", "from_state", "to_state", "state_source", "scope_type", "feature_scope_type", "sector_type", "item_type", "strategy", "index_method", "coverage_level"]:
        if col in out.columns:
            out[col] = out[col].map(display_value)
    return out


def rename_columns_for_display(df):
    if df is None or getattr(df, "empty", True):
        return df
    localized = localize_display_values(df)
    return localized.rename(columns={col: COLUMN_LABELS.get(col, col) for col in localized.columns})
